name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd heavtter-pages
          yarn install || npm install

      - name: Build with Next.js
        run: |
          cd heavtter-pages
          yarn build || npm run build

      - name: List contents of out directory
        run: ls -l heavtter-pages/out

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: heavtter-pages/out
          name: github-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: List contents of out directory
        run: ls
        
      - name: List contents of out directory
        run: ls -l heavtter-pages/out
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: heavtter-pages/out
